# Generated by Django 3.0.10 on 2020-10-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("email", models.CharField(max_length=64)),
                ("tag1", models.CharField(max_length=16)),
                ("tag2", models.CharField(max_length=16)),
                ("tag3", models.CharField(max_length=16)),
                ("is_alias", models.BooleanField(default=False)),
            ],
        ),
    ]
