#!/bin/bash

if [ "$1" = "b" ]; then
    shift
    docker build -t sloppycoder/git-crawler:v0.6 .
fi

source .env

docker run -it -p 8000:8000 -p 8001:8001 \
  -e PG_HOST=$PG_HOST -e PG_PORT=$PG_PORT \
  -e PG_USERNAME=$PG_USERNAME -e PG_PASSWORD=$PG_PASSWORD \
  -e PG_DATABASE=$PG_DATABASE \
  -e REDIS_URI=redis://172.17.0.1:6379 \
  -e DJANGO_SECRET=$DJANGO_SECRET \
  -e KEY_PASSWORD=$KEY_PASSWORD \
  sloppycoder/git-crawler:v0.6 $*

