# Generated by Django 3.0.10 on 2020-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="gitweb_base_url",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
