# Generated by Django 3.0.10 on 2020-10-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='last_error',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
