# Generated by Django 3.0.10 on 2020-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_repository_gitweb_base_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(max_length=512),
        ),
    ]
