# Generated by Django 3.0.10 on 2020-10-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20201014_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configentry',
            options={'verbose_name': 'Config Entry', 'verbose_name_plural': 'Config Entries'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.AlterField(
            model_name='author',
            name='tag1',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='tag2',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='tag3',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='last_error',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('InUse', 'InUse'), ('Error', 'Error')], default='Ready', max_length=8),
        ),
    ]
