# Generated by Django 3.0.10 on 2020-10-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_auto_20201013_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="configentry",
            name="ini",
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
