# Generated by Django 3.0.10 on 2020-10-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20201014_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
