# Generated by Django 3.0.10 on 2020-10-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20201014_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configentry',
            name='ini',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
