# Generated by Django 3.0.10 on 2021-01-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="tag1",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="tag2",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="tag3",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
