name: publish docker images

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build and push image
        uses: docker/build-push-action@v1
        with:
          username: sloppycoder
          password: ${{ secrets.DOCKER_HUB_PASS }}
          repository: sloppycoder/git-crawler
          tag_with_ref: true
